CarpoolWeb/CarpoolWebMVC/Controllers/AuthController.cs
using CarpoolData.DTOAndMapper;
using CarpoolService.Contracts;
using CarpoolService.Exception;
using CarpoolWebMVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Authentication;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CarpoolWebMVC.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService userService;
        private readonly ModelMapper modelMapper;
        private readonly IMailClient mail;
        public AuthController(IUserService userService, ModelMapper modelMapper, IMailClient mail)
        {
            this.userService = userService;
            this.modelMapper = modelMapper;
            this.mail = mail;

        }
        public IActionResult Login()
        {
            return View();
        }
        //public IActionResult Register()
        //{
        //    return View();
        //}

        private async Task<UsersDTO> TryGetUser(string username, string password)
        {
            var user = await this.userService.GetByUsernameAsync(username);

            if (user.Password != password)
            {
                throw new AuthenticationException("Invalid password");
            }
            return user;
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }
            try
            {
                var user = await this.TryGetUser(loginViewModel.Username, loginViewModel.Password);

                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim(ClaimTypes.Role, user.Role)
                };
                var claimsIdentity = new ClaimsIdentity(claims, "Login");

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("Index", "Home");
            }
            catch (EntityNotFoundException ex)
            {

                this.ModelState.AddModelError(nameof(loginViewModel.Username), ex.Message);
                return this.View(loginViewModel);
            }

        }

        //[HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Register()
        {
            var registerViewModel = new RegisterViewModel();

            return this.View(registerViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromForm] RegisterViewModel registerViewModel)
        {
            try
            {

                if (!this.ModelState.IsValid)
                {
                    return this.View(registerViewModel);
                }

                var user = this.modelMapper.ToModel(registerViewModel);

                await this.userService.CreateAsync(user.UserName, user.Password, user.FirstName, user.LastName, user.Email, user.PhoneNumber, user.ValidationCode, registerViewModel.Avatar);
                await mail.SendValidationEmail(user);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {

                return BadRequest(ex.Message);
            }

        }
        public async Task<IActionResult> Error404()
        {
            return this.View();
        }


    }
}

CarpoolWeb/CarpoolWebMVC/Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using CarpoolService.Contracts;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CarpoolWebMVC.Controllers
{
    [Authorize(Roles = "User,Admin")]
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private static Random random = new Random();

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        [HttpGet]
        [Authorize(Roles = "User, Anonymous")]
        public async Task<IActionResult> GetUsersAsync()
        {
            var users = await this.userService.GetAll();

            if (!users.Any())
            {
                return NotFound();
            }

            return this.View(users);
        }
        public async Task<IActionResult> GetUserByIdAsync(int id)
        {
            var user = await this.userService.GetByIdAsync(id);

            if (user == null)
            {
                return NotFound();
            }

            return this.View(user);
        }

        public async Task<IActionResult> UpdateUserAsync(string username)
        {
            var user = await this.userService.GetByUsernameAsync(username);

            return this.View(user);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUserAsync(int userId, string username, string password, string firstName, string lastName, string email, string phoneNumber)
        {
            var user = await this.userService.UpdateAsync(userId, username, password, firstName, lastName, email, phoneNumber);

            if (user == null)
            {
                return NotFound();
            }

            return this.View(user);
        }

        public async Task<IActionResult> CreateUserAsync(string userName, string password, string firstName, string lastName, string email, string phoneNumber, IFormFile avatar)
        {
            try
            {
                var validationString = RandomString(5);
                var user = await this.userService.CreateAsync(userName, password, firstName, lastName, email, phoneNumber, validationString, avatar); ;

                if (user == null)
                {
                    return NotFound(); // should be something like: invalid input
                }

                return this.View(user);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        public async Task<IActionResult> GetByUsernameAsync(string username)
        {
            var user = await this.userService.GetByUsernameAsync(username);

            if (user == null)
            {
                return NotFound();
            }

            return this.View(user);
        }

        public async Task<IActionResult> SearchByEmaileAsync(string email)
        {
            var users = await this.userService.SearchByEmailAsync(email);

            if (!users.Any())
            {
                return NotFound();
            }

            return this.View(users);
        }
        public async Task<IActionResult> GetByPhoneAsync(string phone)
        {
            var user = await this.userService.GetByPhoneAsync(phone);

            if (user == null)
            {
                return NotFound();
            }

            return this.View(user);
        }
        public async Task<IActionResult> FilterByRatingAsync(decimal rating)
        {
            var users = await this.userService.FilterByRatingAsync(rating);

            if (!users.Any())
            {
                return NotFound();
            }

            return this.View(users);
        }
        public async Task<IActionResult> FilterMultipleCriteriaAsync(string firstname, string lastname, string email, string phone, string username)
        {
            var users = await this.userService.MultipleQueryFilterAsync(firstname, lastname, email, phone, username);

            if (!users.Any())
            {
                return NotFound();
            }

            return this.View(users);
        }

        public async Task<IActionResult> DeleteOwnUserAsync(int id)
        {
            await this.userService.DeleteOwnUserAsync(id);

            return this.View(); // Should this return something?
        }

        public async Task<IActionResult> DeleteReviewAsync(int userId, int reviewId)
        {
            await this.userService.DeleteReviewAsync(userId, reviewId);

            return this.View(); // Should this return something?
        }
        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> GetUserCarsAsync(int id)
        {
            var cars = await this.userService.SeeAllHisCarsAsync(id);

            if (!cars.Any())
            {
                return NotFound();
            }

            return this.View(cars);
        }
        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> GetUserRecipientReviewsAsync(int id)
        {
            var reviews = await this.userService.SeeAllHisRecipientReviewsAsync(id);

            if (!reviews.Any())
            {
                return NotFound();
            }

            return this.View(reviews);
        }
        [Authorize(Roles = "User,Admin")]
        public async Task<IActionResult> GetUserAuthorReviewsAsync(int id)
        {
            var reviews = await this.userService.SeeAllHisAuthorReviewsAsync(id);

            if (!reviews.Any())
            {
                return NotFound();
            }

            return this.View(reviews);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> GetAverageRatingAsync(int id)
        {
            var rating = await this.userService.AverageRatingAsync(id);

            if (rating == default(decimal))
            {
                return NotFound();
            }

            return this.View(rating);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> CreateReviewAsync(int userId, int recipientId, string comment, decimal rating)
        {
            var review = await this.userService.LeaveReviewAsync(userId, recipientId, comment, rating);

            if (review == null)
            {
                return NotFound();
            }

            return this.View(review);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> EditReviewAsync(int userId, int reviewId, string comment, decimal rating)
        {
            var review = await this.userService.EditReviewAsync(userId, reviewId, comment, rating);

            if (review == null)
            {
                return NotFound();
            }

            return this.View(review);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> OwnerTravelHistoryAsync(int id)
        {
            var travels = await this.userService.OwnTravelHistory(id);

            if (!travels.Any())
            {
                return NotFound();
            }

            return this.View(travels);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> GetAllRecipientRequest(int recipientId)
        {
            var requests = await this.userService.SeeAllHisRecipientRequestAsync(recipientId);

            if (!requests.Any())
            {
                return NotFound();
            }

            return this.View(requests);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> GetAllAuthorRequest(int authorId)
        {
            var requests = await this.userService.SeeAllHisAuthorRequestAsync(authorId);

            if (!requests.Any())
            {
                return NotFound();
            }

            return this.View(requests);
        }
        [Authorize(Roles = "User,Admin")]

        public async Task<IActionResult> CreateTravelRequest(int authorId, int recipientId, int travelId)
        {
            var request = await this.userService.CreateRequestAsync(authorId, recipientId, travelId);

            if (request == null)
            {
                return NotFound();
            }

            return this.View(request);
        }

        public async Task<IActionResult> RespondToTravelRequest(int recipientId, int requestId, bool answer)
        {
            var request = await this.userService.EditRequestAsync(recipientId, requestId, answer);

            if (request == null)
            {
                return NotFound();
            }

            return this.View(request);
        }

        public async Task<IActionResult> DeleteTravelRequest(int authorId, int requestId)
        {
            await this.userService.DeleteRequestAsync(authorId, requestId);

            return this.View(); // Should this return something?
        }
        public static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}

CarpoolWeb/CarpoolWebMVC/Views/Shared/_Layout.cshtml
@using CarpoolService.Contracts
@using System.Security.Claims;
@inject IUserService userService

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarpoolWebMVC</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="assets/images/icon/favicon.ico">
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/metisMenu.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/slicknav.min.css">
    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <!-- others css -->
    <link rel="stylesheet" href="~/css/typography.css">
    <link rel="stylesheet" href="~/css/default-css.css">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <link rel="stylesheet" href="~/css/styleHome.css">
    <link rel="stylesheet" href="~/css/site.css">
    <!-- modernizr css -->
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-custom navbar-mainbg">
            <a class="navbar-brand navbar-logo" href="#">APT</a>
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars text-white"></i>
            </button>

            @if (User.Identity.IsAuthenticated)
            {
                var user = await userService.GetByUsernameAsync(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name).Value);

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar-list-4">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                <img src="@user.ProfileImage" width="40" height="40" class="rounded-circle">
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="User" asp-action="UpdateUser" asp-route-username="@user.Username">Edit Profile</a>
                            </div>
                        </li>
                    </ul>
                </div>



                @*<div>
                        <a asp-controller="User" asp-action="GetByUsername" asp-route-username="@user.Username">
                            <img href="@user.ProfileImage" />
                        </a>
                    </div>*@
            }


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="hori-selector">
                    <div class="left">
                    </div>
                    <div class="right">
                    </div>
                </div>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item" id="HomeIndex">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item" id="TravelTravel">
                            <a class="nav-link" asp-controller="User" asp-action="FilterMultipleCriteria">User</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0);"><i class="far fa-calendar-alt"></i>Travel</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item" id="AuthLogin">
                            <a class="nav-link" asp-controller="Auth" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item" id="AuthLogin">
                            <a class="nav-link" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    }


                    <li class="nav-item" id="AuthRegister">
                        <a class="nav-link" asp-controller="Auth" asp-action="Register">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - APT - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <!-- bootstrap 4 js -->
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/metisMenu.min.js"></script>
    <script src="~/js/jquery.slimscroll.min.js"></script>
    <script src="~/js/jquery.slicknav.min.js"></script>
    <script src="~/js/site.js"></script>

    <!-- others plugins -->
    <script src="~/js/plugins.js"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>